### PR TITLE
Generate Angular client from OpenAPI spec 

### PR DESCRIPTION
**Pull request by sfc-gh-krzymkowski**
`npm run generate-api` will regenerate `src/api` from backend running at `http://localhost:8080`

Setup is in first commit. Second commit are the generated files.

### CODE REVIEW

**Comment by Vodzoo** [comment]
In environment.prod.ts add key for base path to api:
```apiUrl: ''```
and in main module set provider for BASE_PATH injection token -> environment.apiUrl
Default path is localhost:8080 so we don't need to set this value in environment.ts.

**Comment by sfc-gh-krzymkowski** [comment]
> In environment.prod.ts add key for base path to api: `apiUrl: ''` and in main module set provider for BASE_PATH injection token -> environment.apiUrl Default path is localhost:8080 so we don't need to set this value in environment.ts.

Very good point!
I achieved this a bit differently - https://github.com/coi-gov-pl/gui-web-pomogamukrainie-forum/pull/28/commits/73e66cfa00bf3873488a0b76ea4a84a6016a4798

**Comment by sfc-gh-krzymkowski** [comment]
There's one problem left: the methods are called `list4`, `list5`, etc. That's because the operation names are generated from local java method names that are often called the same (`list`). This produces multiple operations with same name and the generator appends numbers to them :( 
It can be mitigated by giving uniq operation id to all the controller methods via `@Operation(operationId="...")` or by naming the methods themselves uniquely

**Comment by archiewald** [comment]
would love to see an example if that works in some component. We can try cityLookup after https://github.com/coi-gov-pl/gui-web-pomogamukrainie-forum/pull/26 is merged

**Review by sfc-gh-akozubek — APPROVED** [review]

**Pull request merged**
