### PR TITLE
Add default query params to category navigation.

### PR DESCRIPTION
**Pull request by felix1313**
Add default query params to category navigation buttons. With non-empty query params the request will be performed and initial data will be fetched.

### CODE REVIEW

**Comment by bbartosiak** [comment]
duplicate:
https://github.com/coi-gov-pl/gui-web-pomogamukrainie-forum/pull/119

**Comment by felix1313** [comment]
Not really. The data was not fetched onInit if there are no query params. 

 if (page != null || size != null || capacity != null || city != null || region != null) { // all is null without this CL
      this.search(searchCriteria);
    }

This PR adds default query params.

**Review by broslukasz — APPROVED** [review]

**Comment by felix1313** [comment]
@bbartosiak any comments? 
Do you think it's a duplicate? Should we merge it?

**Comment by mgol** [comment]
@felix1313 Bartek wrote to me that maybe we should get https://github.com/coi-gov-pl/gui-web-pomogamukrainie-forum/pull/148 landed first.

**Comment by bbartosiak** [comment]
something wrong, run rebase/merge with the main branch

**Comment by felix1313** [comment]
Opened #181 instead.

**Pull request closed without merging**
